version: '3'
services:
  #Application Dockerfile is in the same folder or '.'
  app:
    build: .

    #db is db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
